name: mxmcsc
favicon: null
layout_spectrum: 0.5777783442754298
typography_spectrum: 0.9302206477150321
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.8207954030949622
  lightness: 0.4732106684241444
  saturation: 0.114174441434443
  rhythmicContrast: 0.292018722044304
purpose: []
